### ISSUE TITLE
Fails to create camera for thorlabs cs165mu1

### ISSUE THREAD

**Issue by ileGITimo** [matham/thorcam#10]
Trying the simple example with a CS165MU1 cameera, I get an error when opening it:
>>> cam.refresh_cameras()
>>> EDT pdv open failed.
Check board installation and unit number, and try restarting the computer
Received "serials" with value "['17044']"
cam.open_camera('17044')
>>> ERROR:root:TLCamera2: tl_camera_get_data_rate: Neither fps nor readout frequency is supported. Error: Unsupported parameter or camera feature.
   at Thorlabs.TSI.TLCamera.TLCamera2.get_DataRate()
ERROR:root:Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\thorcam\camera_dot_net.py", line 432, in camera_run
    settings = self.read_settings(cam)
  File "C:\Python37\lib\site-packages\thorcam\camera_dot_net.py", line 234, in read_settings
    d['freq'] = self._freqs_to_str_map[cam.get_DataRate()]
System.InvalidOperationException: TLCamera2: tl_camera_get_data_rate: Neither fps nor readout frequency is supported. Error: Unsupported parameter or camera feature.
   at Thorlabs.TSI.TLCamera.TLCamera2.get_DataRate()

Received "exception" with value "['TLCamera2: tl_camera_get_data_rate: Neither fps nor readout frequency is supported. Error: Unsupported parameter or camera feature.\n   at Thorlabs.TSI.TLCamera.TLCamera2.get_DataRate()', 'Traceback (most recent call last):\n  File "C:\\Python37\\lib\\site-packages\\thorcam\\camera_dot_net.py", line 432, in camera_run\n    settings = self.read_settings(cam)\n  File "C:\\Python37\\lib\\site-packages\\thorcam\\camera_dot_net.py", line 234, in read_settings\n    d[\'freq\'] = self._freqs_to_str_map[cam.get_DataRate()]\nSystem.InvalidOperationException: TLCamera2: tl_camera_get_data_rate: Neither fps nor readout frequency is supported. Error: Unsupported parameter or camera feature.\n   at Thorlabs.TSI.TLCamera.TLCamera2.get_DataRate()\n']"
Received "cam_closed" with value "None"

**Comment by matham** [comment]
I guess I have not foreseen that there may be a camera that doesn't support a frame rate at all. Try uncommenting out this line in your install thorcam: https://github.com/matham/thorcam/blob/master/thorcam/camera_dot_net.py#L234=.

**Comment by ileGITimo** [comment]
Commenting out that line makes the example work.

cam.open_camera('17044')
>>> Received "settings" with value "{'binning_x': 1, 'binning_x_range': [1, 16], 'binning_y': 1, 'binning_y_range': [1, 16], 'black_level': 1, 'black_level_range': [0, 511], 'color_gain': [1, 1, 1], 'exposure_ms': 40.001, 'exposure_range': [0.04, 26843.432], 'frame_queue_size': 1, 'gain': 0, 'gain_range': [0, 480], 'roi_height': 1080, 'roi_width': 1440, 'roi_x': 0, 'roi_y': 0, 'sensor_size': [1440, 1080], 'supported_freqs': ['30 FPS'], 'supported_taps': [], 'supports_color': False, 'taps': '', 'trigger_count': 0, 'trigger_type': 'SW Trigger'}"
Received "cam_open" with value "None"

**Comment by matham** [comment]
Got a related report from someone:

```
ERROR:root:TLCamera2: tl_camera_get_gain: Gain is not supported. Error: Unsupported parameter or camera feature.
   at Thorlabs.TSI.TLCamera.TLCamera2.get_Gain()
ERROR:root:Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\thorcam\camera_dot_net.py", line 432, in camera_run
    settings = self.read_settings(cam)
  File "C:\Program Files\Python37\lib\site-packages\thorcam\camera_dot_net.py", line 216, in read_settings
    d['gain'] = cam.get_Gain()
System.InvalidOperationException: TLCamera2: tl_camera_get_gain: Gain is not supported. Error: Unsupported parameter or camera feature.
   at Thorlabs.TSI.TLCamera.TLCamera2.get_Gain()
```

I'll need to work out a way to only get parameters if the camera supports it.

**Comment by matham** [comment]
I made a new release that should fix the issues. Please try it and let me know if it didn't fix it.

**Comment by ileGITimo** [comment]
Seems to work, but:
If I type a subset of the example lines into python it finds my camera
```
C:\tmp>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from thorcam.camera import ThorCam
>>>
>>> class MyThorCam(ThorCam):
...     def received_camera_response(self, msg, value):
...         super(MyThorCam, self).received_camera_response(msg, value)
...         if msg == 'image':
...             return
...         print('Received "{}" with value "{}"'.format(msg, value))
...     def got_image(self, image, count, queued_count, t):
...         print('Received image "{}" with time "{}" and counts "{}", "{}"'
...               .format(image, t, count, queued_count))
...
>>> cam = MyThorCam()
>>> cam.start_cam_process()
>>> cam.refresh_cameras()
>>> EDT pdv open failed.
Check board installation and unit number, and try restarting the computer
Received "serials" with value "['17044']"
print(cam.serials)
['17044']
>>> cam.stop_cam_process()
False
>>> quit()
```

If I save all the lines I typed above to a file and run  "python file" it doesn't find the file:
C:\tmp>python thor_cam.py
[]
EDT pdv open failed.
Check board installation and unit number, and try restarting the computer

The empty serials[] comes out empty, probably before refresh is done.  It is like there's no synchronization between threads and in the interactive session it gets a slot to run before I type the print line, but in execution mode it doesn't get a slot in time.

**Comment by matham** [comment]
That's because none of these functions are synchronous. You need to wait for the process to be fully started. Then `received_camera_response` is how you respond to a serials refresh, so you need to wait for that function to be called. If you don't wait, the script will exit before any of that happened.
